Repository NOAA-EMC/gdas-marine-viz, pull requests merged in 2025-04, with the labels that each got.

#514 Improve letkf obsstats diags and some bugfixes
  applications/cycle_diagnostics/letkf_obsstats.py
  applications/cycle_diagnostics/vrfy_script.py
  applications/obsstats_ts/gdassoca_obsstats.py
Labels: soca, gfsv17, gfsv18

#516 Better ranges for some plots, thicker lines
  applications/cycle_diagnostics/vrfy_script.py
  applications/obsstats_ts/gdassoca_obsstats.py
Labels: gfsv17

#517 Add extra EVA map_plots: OmA, hofx, ObsError, ObsTime
  applications/cycle_diagnostics/marine_eva_post.py
  configs/marine_gdas_plots.yaml
  requirements.txt
Labels: soca, gfsv17

#519 Added back the density plots
  applications/oceanview/oceanview.py
Labels: soca, gfsv17
